name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      -main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build-and-test:
    name: Build and Test project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hasFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Makefile Permissions
        run: chmod +x Makefile

      - name: Ensure Gradle Wrapper
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi

      - name: Run Pipeline
        run: make pipeline